### ISSUE TITLE
Style declaration including only `null` values result in errors being thrown

### ISSUE THREAD

**Issue by RimanDk** [nonzzz/vite-plugin-stylex#10]
**The problem**
Style objects that include only entries with `null` values result in `stylex.create should never be called. It should be compiled away.` exception.

**How to reproduce**
Steps to reproduce:
1. Create a React + TypeScript project with StyleX
2. Create a style block/declaration including only `null` values, f.ex:
```
const styles = stylex.create({
  test: {
    padding: null,
  }
});
```
3. Apply to any node in a given component

[Code Sandbox example](https://codesandbox.io/p/devbox/stylex-issue-wr8hxp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrailb8a00073b6jsxy53szt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrailb8a00023b6jxyx8kl5m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrailb8a00043b6jy42n2odu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrailb8a00063b6j2pxqw62x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrailb8a00023b6jxyx8kl5m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrailb8900013b6jknxbz99t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clrailb8a00023b6jxyx8kl5m%2522%252C%2522activeTabId%2522%253A%2522clrailb8900013b6jknxbz99t%2522%257D%252C%2522clrailb8a00063b6j2pxqw62x%2522%253A%257B%2522id%2522%253A%2522clrailb8a00063b6j2pxqw62x%2522%252C%2522activeTabId%2522%253A%2522clrailb8a00053b6jea3du8w1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrailb8a00053b6jea3du8w1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clraimgad00b33b6jpeaz7duv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrailb8a00043b6jy42n2odu%2522%253A%257B%2522id%2522%253A%2522clrailb8a00043b6jy42n2odu%2522%252C%2522activeTabId%2522%253A%2522clrailb8a00033b6jhuxffjer%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrailb8a00033b6jhuxffjer%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clraioci900kr3b6jijvvgu7u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clraiockd003teeip17zb9hqq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) (expand console in the browser window - might need a reload to show up)

**Comment by nonzzz** [comment]
I think you should link this issue to stylex, `vite-plugin-stylex-dev` is a wrapper for vite. If stylex don't allowed this edge case, this plugin also can't.

**Comment by RimanDk** [comment]
> I think you should link this issue to stylex, `vite-plugin-stylex-dev` is a wrapper for vite. If stylex don't allowed this edge case, this plugin also can't.

They pointed me to you =)

https://github.com/facebook/stylex/issues/344

**Comment by nonzzz** [comment]
@RimanDk Ok, I will check it thanks for you report

**Comment by RimanDk** [comment]
> @RimanDk Ok, I will check it thanks for you report

Thank you! 🙏

**Comment by nonzzz** [comment]
I fixed it. The new version has been released, even if the style is empty the result should still be returned.

**Comment by RimanDk** [comment]
> I fixed it. The new version has been released, even if the style is empty the result should still be returned.

Indeed, appears to be resolved! Thank you! Much appreciated!
