### ISSUE TITLE
Preload styles via <link rel="stylesheet" />

### ISSUE THREAD

**Issue by predaytor** [nonzzz/vite-plugin-stylex#11]
With Vite's future support for `.css?url` imports, will it be possible to enable manual preloading for styles? For example, using Remix:
```jsx
export const links = () => [
	// Preload CSS as a resource to avoid render blocking
	{ rel: 'preload', href: stylesHref, as: 'style' },

	// These should match the css preloads above to avoid css as render blocking resource
	{ rel: 'stylesheet', href: stylesHref },
];
```

**Comment by nonzzz** [comment]
Well,Is there any document or information for this feature request? I'm currently can't get any information about `.css?url` from vite document. I think we need more details.

**Comment by nonzzz** [comment]
Currently, for production mode, the plugin injects style behavior using vite's `css-post` plugin. This means that the insertion order and injected tag attributes are controlled by vite.
I assume this feature request is for SSR. If vite supports `.css?url` in the future, I can support it.

**Comment by predaytor** [comment]
Sorry I didn't mention it, here is the PR: https://github.com/vitejs/vite/pull/15259. Thanks for reply. Looking forward to use StyleX on the next project.

**Comment by predaytor** [comment]
With the release of Vite 5.1, how can we implement this?

**Comment by nonzzz** [comment]
Well, I'll do it as soon as possible.

**Comment by nonzzz** [comment]
@predaytor See [remix-demo](https://github.com/nonzzz/vite-plugin-stylex/tree/master/examples/remix-demo) get more information.

**Comment by nonzzz** [comment]
I think this feature is already supported. Can we turn it off?

**Comment by predaytor** [comment]
All is working perfectly, HMR, everything! Very thx!
