### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by BMCwebdev** [nonzzz/vite-plugin-stylex#12]
Everything seems to be working when I run the build, but not when I `npm run dev` in my app.

My app is importing a component library that I have created. This library is using StyleX. It does not compile StyleX into the build though. The vite.config in the component library has this in the plugins section
```
...(command !== 'build' ? [stylexPlugin()] : []), // Only include stylexPlugin when not building
```
I thought I would not want to compile the component library, and rather the user of it would need to have stylex installed and they would compile.

As I said, works when running the build. Not when running `npm run dev`

**Comment by nonzzz** [comment]
AFAIK i think it can be work well in current version. I'm not sure your component library has export the esm format. I used monorepo and created a minimal reproduction, Nothing happened. If you component library only export cjs format. I think you can using `vite-plugin-commonjs` or export `esm` format.

**Comment by nonzzz** [comment]
[demo-page](https://github.com/nonzzz/vite-plugin-stylex/blob/master/examples/vite-demo/src/app.vue) Here is a minimal reproduction. Notice package `text` is a full cjs package. So i add `vite-plugin-commonjs` to handle it. And the package `button` is a full esm pacakge.It's work well.

**Comment by BMCwebdev** [comment]
Thanks for the reply, @nonzzz . The component library is ES bundled. I've attached a copy to this (I added `.txt` to the end of the name so that github would allow me to attach the file).

In the component library, both `npm run build` and `npm run dev` work. But in the app `npm run dev` does not, while `npm run build` does appear to work (at least I don't get errors and the static css file is generated).

I've tried adding optimizeDeps and a rollup build option to the vite.config in case it was due to Vite not compiling dependencies during `npm run dev`

`vite.config.ts`
```
/// <reference types="vite/client" />

import { vitePlugin as remix } from '@remix-run/dev';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import { stylexPlugin } from "vite-plugin-stylex-dev";

export default defineConfig({
  plugins: [stylexPlugin(), remix(), tsconfigPaths()],
  optimizeDeps: {
    include: ["@componentLib/componentLib-ui"],
  },
  build: {
    rollupOptions: {
      plugins: [stylexPlugin()],
    },
  },
});
```

[componentlib-ui.es.js.txt](https://github.com/nonzzz/vite-plugin-stylex/files/14594074/componentlib-ui.es.js.txt)

**Comment by nonzzz** [comment]
Some ideas, i download your component bundle and create a sub module in my local machine and using it in remix application. But i found interesting is that in monorepo, sub module won't be pre build in vite. ( so it can be work well) Others module has been pre build by vite pre build phase. I think you can try using `exclude` instead of `include`.  AFAIK stylex need compiler but vite pre build logic will break this behavior because vite doesn't know how to use babel's parse for stylex.

**Comment by nonzzz** [comment]
`vite-plugin-stylex` follow stylex, So all of chunk who contain `stylex` will be transformed at `transform` phase.

**Comment by BMCwebdev** [comment]
Tried your suggestions, no luck. Perhaps this is due to the new vitePlugin from Remix, I am not using the old unstable_vitePlugin.

**Comment by BMCwebdev** [comment]
I've been trying all the stylex vite plugins. I got it working using HorusGoul, but this might work for yours as well. I'll give it a try later. But in vite.config I added
```
  ssr: {
    noExternal: ['@acme/library-ui'],
  },
```
I am not using any other config option (no build rollup option, no optimizeDeps options).

**Comment by BMCwebdev** [comment]
Hmmm, not sure `ssr noExternal` actually fixed anything.

**Comment by nonzzz** [comment]
I'll test noExternal in ssr mode and get to know what happened on it. All of my options will be recorded here.

**Comment by nonzzz** [comment]
After my test. `optimizeDeps` and `ssr.noExternal` must be set at the same time. Can you have a try? If it can work. I'll update the document to describe it.

**Comment by nonzzz** [comment]
<img width="646" alt="image" src="https://github.com/nonzzz/vite-plugin-stylex/assets/52351095/c7f7cbf9-e891-47ae-a7f9-0ea4eeeb7c66">
Using `optmizeDeps` to prevent vite from packaging stylex, and `ssr.noExternal` is work for es module syntax can work well.

**Comment by BMCwebdev** [comment]
Hey nonzzz, horusgoul updated his plugin and it seems to have done the trick. Not sure if you want to take a look at his changes and if they would be applicable to your plugin as well. Thank you for all the help!

**Comment by nonzzz** [comment]
I create a new version. Add new option `optimizedDeps` for this scene.
