### ISSUE TITLE
add support for react-strict-dom as stylex soucre

### ISSUE THREAD

**Issue by advancedtw** [nonzzz/vite-plugin-stylex#13]
configuring the plugin as shown below doesn't seem to be sufficient. 
```ts
importSources: [{ from: 'react-strict-dom', as: 'css '}]
```

I'm not sure what else is required to make it work.

**Comment by advancedtw** [comment]
I see what is the issue styleXTransform is not passing the importSources to  stylexBabelPlugin.  
Simply forwarding the importSource and adding ```optimizedDeps: ["react-strict-dom"]``` in the config can make it work.

**Comment by nonzzz** [comment]
Thank for you report. A fix patch is pushed.

**Comment by nonzzz** [comment]
@advancedtw  `v0.4.1` has been released.
