### ISSUE TITLE
LightningCSS does not work in dev mode (HMR)

### ISSUE THREAD

**Issue by predaytor** [nonzzz/vite-plugin-stylex#14]
Stackblitz (https://stackblitz.com/edit/remix-run-remix-3gnvyb?file=app%2Froutes%2F_index.tsx)

Post-processing with LightningCSS does not work in dev mode on HMR updates. The production build works as expected.
```tsx
const styles = stylex.create({
  x: {    
     color: 'lch(from pink calc(l + 10%) c h)',  
  },
});
```
css output:
```css
color: lch(from pink calc(l + 10%) c h);
```
should be:
```css
color: lch(from pink calc(l + 10%) c h);
color: lab(93.7873% 24.4367 3.75943);
```
Notice the defined CSS in the regular imported stylesheet (in our case the main import `/styles/index.css`), the post-processing is working properly.

**Comment by nonzzz** [comment]
I might think is a bug for lightningCSS. According [lch](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch) I think expression `calc(1 + 10%)` not correct syntax. But lightningCSS can make it work well. These are all digressions.

It's a bug for the plugin. I have been fixed this issue in my local. But i need to ensure all of scene can be passed.

**Comment by nonzzz** [comment]
All related issues will be work at [fix](https://github.com/nonzzz/vite-plugin-stylex/tree/fix/issue)
