### ISSUE TITLE
@stylex/open-props import (bug)

### ISSUE THREAD

**Issue by Lukjuh** [nonzzz/vite-plugin-stylex#3]
When importing the `@stylexjs/open-props` package im getting this error:

```
chunk-AEPY33DS.js?v=df81b0f4:401 Uncaught Error: stylex.defineVars should never be called. It should be compiled away.
    at stylexDefineVars (chunk-AEPY33DS.js?v=df81b0f4:401:13)
    at @stylexjs_open-props_lib_colors__stylex.js?v=e2f9464a:10:43
```

```tsx
import * as stylex from "@stylexjs/stylex";
import { colors } from "@stylexjs/open-props/lib/colors.stylex";

const styles = stylex.create({
  base: {
    color: colors.blue11,
  },
});

function Button() {
  return <button {...stylex.props(styles.base)}>Click me!</button>;
}

export { Button };

```

```tsx
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { stylexPlugin } from "vite-plugin-stylex-dev";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), stylexPlugin()],
});

```

**Comment by denexapp** [comment]
I get the same error with the default vite react typescript template. 

I made a sandbox to reproduce the error: https://stackblitz.com/edit/vitejs-vite-bmmdyh

**Comment by nonzzz** [comment]
Sry for late, I property know why reason cause it. Here is a relative issue https://github.com/facebook/stylex/issues/112.
In vite,vite will do a pre build in development. so stylex can't get the right entry to process. https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude look it, currently stylex don't provide esm so we can't use optimization :(

**Comment by nonzzz** [comment]
I think it not a bug and i create https://github.com/facebook/stylex/discussions/258

**Comment by Lukjuh** [comment]
Maybe this is helping: https://github.com/HorusGoul/vite-plugin-stylex/issues/23

**Comment by nonzzz** [comment]
@Lukjuh I know, As a temporary solution I can solve it but I feel it is right for stylex to solve it

**Comment by nonzzz** [comment]
I release v0.1.3 try it plz.

**Comment by hipstersmoothie** [comment]
Still hitting this
