### ISSUE TITLE
[plugin:vite-plugin-stylex] C:\Users\Arun\Documents\GitHub\black\packages\frontend\src\components\buttons\Button.tsx: Only static values are allowed inside of a stylex.create() call.

### ISSUE THREAD

**Issue by arunnan** [nonzzz/vite-plugin-stylex#4]
Created tokens.stylex.ts as below.

```
import * as stylex from '@stylexjs/stylex';

const DARK = "@media (prefers-color-scheme: dark)";

export const colors = stylex.defineVars({ 
    primary: {default: '#fff', [DARK]: '#000'},
    primaryDark: {default: '#ccc', [DARK]: '#333'},
    bg: {default: '#fff', [DARK]: '#000'},
    white: {default: '#fff', [DARK]: '#000'},
    black: {default: '#000', [DARK]: '#fff'}
})
```

and Buttons.tsx as below

```
import * as stylex from '@stylexjs/stylex';
import { ComponentProps } from "react";
import { colors } from 'src/components/tokens.stylex';

type ButtonProps = {
    variant?: "primary",
    children?: React.ReactNode,
    styles?: stylex.StyleXStyles,
} & ComponentProps<"button">

const baseStyle = {
    borderWidth: '1px',
    borderStyle: 'solid',
    color: colors.white,
    borderRadius: '5px',
    cursor: 'pointer',
    padding: '10px 15px'
};

const s = stylex.create({
    base: baseStyle,
    primary: {
        borderColor: {
            default: colors.primary
        },
        color: {
            default: colors.black
        },
        backgroundColor: {
            default: colors.primary,
            ':hover': colors.primaryDark,
            ':focus': colors.primaryDark,
            ':active': colors.primaryDark,
        },
    }
});

const Button = ({ variant = "primary", styles, ...props }: ButtonProps) => (
    <button {...stylex.props(s.base, s[variant], styles)} {...props} />
);

export default Button;
```

I am getting the below error

`[plugin:vite-plugin-stylex] C:\Users\Arun\Documents\GitHub\black\packages\frontend\src\components\buttons\Button.tsx: Only static values are allowed inside of a stylex.create() call.`

Is it an existing issue? or kindly suggest a fix.

**Comment by nonzzz** [comment]
Version info? I copy your code in a new repo and work fine with `0.1.3`

**Comment by arunnan** [comment]
Thank you. It was resolved when I used a relative path for imports. 
[https://github.com/facebook/stylex/issues/259](https://github.com/facebook/stylex/issues/259)

**Comment by nonzzz** [comment]
Is there any problem?

**Comment by arunnan** [comment]
Hi @nonzzz, I am using the below versions
```
"vite": "^5.0.0",
"vite-plugin-stylex": "^0.4.0"
```
I am reopening this issue, as I am facing inconsistency in button style while importing colors(stylex.defineVars). I will also check the same in CRA.

**Comment by nonzzz** [comment]
I think you need to provide a minimal reproduction.

**Comment by arunnan** [comment]
When I use the imported colors, the entire button style is removed. I am not able to use the values from defineVars.

**Comment by nonzzz** [comment]
I will release a new version in the near future. I made a temporary patch about this problem until stylex officially supports it.

**Comment by nonzzz** [comment]
Hi, I release `v0.2.0` it support path alias :)
