### ISSUE TITLE
Issue on watch production build.

### ISSUE THREAD

**Issue by hendry91** [nonzzz/vite-plugin-stylex#5]
I'm working on a microfrontend project using vite-federation, and I need to rebuild every time to let the host gets the latest dist files. but when I use watchBuild, if I update the Stylex value, I encounter the following error: **[vite-plugin-stylex] Could not load vite-plugin:stylex.css (imported by src/hdd/core/Spinner/BaseSpinner.tsx): rule is not iterable**.

Below are my run scripts:

```
"scripts": {
  "build": "tsc && vite build",
  "preview": "vite preview --port 3001 --strictPort",
  "watchBuild": "concurrently \"pnpm build --watch\" \"pnpm wait-build && sleep 5 && pnpm preview\"",
  "wait-build": "wait-on dist/assets",
}
```

Could you advice on how to let the stylex can be rebuild on --watch? Thanks.

**Comment by nonzzz** [comment]
I'll take a look

**Comment by nonzzz** [comment]
@hendry91 A friendly ping. `v0.3.0` has been released. I think this problem has been solved.

**Comment by bsconnor** [comment]
> @hendry91 A friendly ping. `v0.3.0` has been released. I think this problem has been solved.

Still experiencing this issue on 0.6.0
